import { Message } from 'ai';
import pb from './pocketbase.client';

// Chat schema for PocketBase
// Collection: chats
// Fields:
// - id (auto-generated by PocketBase)
// - messages (json)
// - created (auto-generated by PocketBase)
// - updated (auto-generated by PocketBase)
// - user (relation - links to users collection)

/**
 * Creates a new chat for a user or returns existing one
 */
export async function createOrGetUserChat(userId: string): Promise<string> {
  try {
    // First check if user already has a chat
    const existingChat = await getUserChat(userId);
    if (existingChat) {
      console.log(`User ${userId} already has chat: ${existingChat}`);
      return existingChat;
    }
    
    // If not, create a new chat associated with the user
    const record = await pb.collection('chats').create({
      messages: "[]", // PocketBase expects a string for JSON fields
      user: userId
    });
    
    console.log(`Created new chat for user ${userId} with ID: ${record.id}`);
    return record.id;
  } catch (error) {
    console.error(`Error creating chat for user ${userId}:`, error);
    throw new Error('Failed to create new chat');
  }
}

/**
 * Checks if a chat exists by ID
 */
export async function chatExists(id: string): Promise<boolean> {
  try {
    await pb.collection('chats').getOne(id);
    return true;
  } catch (error) {
    console.log(`Chat ${id} does not exist:`, error);
    return false;
  }
}

/**
 * Gets a user's chat ID
 */
export async function getUserChat(userId: string): Promise<string | null> {
  try {
    console.log(`Looking for chat for user: ${userId}`);
    
    const records = await pb.collection('chats').getList(1, 1, {
      filter: `user = "${userId}"`,
      sort: '-created'
    });
    
    if (records.items.length > 0) {
      const chatId = records.items[0].id;
      console.log(`Found chat ${chatId} for user ${userId}`);
      return chatId;
    }
    
    console.log(`No chat found for user ${userId}`);
    return null;
  } catch (error) {
    console.error(`Error getting chat for user ${userId}:`, error);
    return null;
  }
}

/**
 * Loads chat messages by chat ID
 */
export async function loadChat(id: string): Promise<Message[]> {
  try {
    console.log(`Loading chat messages for ID: ${id}`);
    
    const record = await pb.collection('chats').getOne(id);
    
    console.log(`Successfully retrieved chat record: ${record.id}`);
    
    // Handle both string and already parsed JSON
    let messages: Message[] = [];
    if (typeof record.messages === 'string') {
      console.log('Messages stored as string, parsing JSON');
      messages = JSON.parse(record.messages || '[]');
    } else {
      console.log('Messages already in object format');
      messages = record.messages || [];
    }
    
    console.log(`Loaded ${messages.length} messages from chat ${id}`);
    return messages;
  } catch (error) {
    console.error(`Error loading chat ${id}:`, error);
    
    // Log more details if available
    if (error instanceof Error) {
      console.error('Error details:', {
        name: error.name,
        message: error.message,
        stack: error.stack,
      });
    }
    
    // Return empty array for graceful degradation
    return [];
  }
}

/**
 * Loads chat messages by user ID
 */
export async function loadUserChat(userId: string): Promise<{ chatId: string | null, messages: Message[] }> {
  try {
    console.log(`Loading chat for user ID: ${userId}`);
    
    const chatId = await getUserChat(userId);
    if (!chatId) {
      console.log(`No chat found for user ${userId}`);
      return { chatId: null, messages: [] };
    }
    
    const messages = await loadChat(chatId);
    return { chatId, messages };
  } catch (error) {
    console.error(`Error loading chat for user ${userId}:`, error);
    return { chatId: null, messages: [] };
  }
}

/**
 * Saves chat messages
 */
export async function saveChat({
  id,
  userId,
  messages,
}: {
  id?: string;
  userId?: string;
  messages: Message[];
}): Promise<string> {
  try {
    // If we have an ID, try to update that chat
    if (id) {
      const exists = await chatExists(id);
      
      if (exists) {
        // Update existing chat
        await pb.collection('chats').update(id, {
          messages: JSON.stringify(messages),
        });
        
        return id;
      }
    }
    
    // If we have a userId but no valid id, try to get or create a user chat
    if (userId) {
      const chatId = await createOrGetUserChat(userId);
      
      // Update the chat with the messages
      await pb.collection('chats').update(chatId, {
        messages: JSON.stringify(messages),
      });
      
      return chatId;
    }
    
    // If we don't have either id or userId, create a new chat without a user
    const record = await pb.collection('chats').create({
      messages: JSON.stringify(messages),
    });
    
    console.log(`Created new chat with ID: ${record.id}`);
    return record.id;
  } catch (error) {
    console.error(`Error saving chat:`, error);
    throw new Error('Failed to save chat');
  }
}

/**
 * Clears chat messages for a user
 */
export async function clearUserChat(userId: string): Promise<boolean> {
  try {
    console.log(`Clearing chat for user: ${userId}`);
    
    const chatId = await getUserChat(userId);
    if (!chatId) {
      console.log(`No chat found to clear for user ${userId}`);
      return false;
    }
    
    // Update the chat with empty messages
    await pb.collection('chats').update(chatId, {
      messages: "[]",
    });
    
    console.log(`Successfully cleared chat for user ${userId}`);
    return true;
  } catch (error) {
    console.error(`Error clearing chat for user ${userId}:`, error);
    return false;
  }
}
