'use server'

import * as dotenv from 'dotenv';
import axios from 'axios';
import pb, { authenticatedCall } from '@/app/lib/pocketbase';
import { orderSchema } from '@/app/lib/validations/orders';
import { appendFileSync } from 'fs';
import { getDefaultDeliveryMethod } from '../[locale]/settings/actions/delivery-methods';

dotenv.config();

interface EpicentrOrderMedia {
  id: number;
  externalId: string;
  source: string;
  image: string;
  thumb: string;
  isMain: boolean;
  type: string;
  order: number;
}

interface EpicentrOrderProduct {
  id: number;
  status: string;
  slug: string;
  completeness: number;
  modelId: number;
  media: EpicentrOrderMedia[];
  sku: string;
  price: number;
  availability: number;
  createdAt: string;
  updatedAt: string; //TODO: compare this witn my pb data, if they change i need update my oreder
  publishedAt: string;
}

interface EpicentrOrderItem {
  offerId: string;
  productId: string;
  productExternalId: string;
  sku: string;
  title: string;
  image: string;
  url: string;
  price: number;
  quantity: number;
  subtotal: number;
  measure: string;
  ratio: number;
  product: EpicentrOrderProduct;
}

interface EpicentrOrderAddress {
  firstName: string;
  lastName: string;
  patronymic: string;
  email: string;
  phone: string;
  shipment: {
    provider: string;
    paymentProvider: string;
    paymentStatus: string;
    settlementId: string;
    officeId: string;
    number: string;
    isFree: boolean;
    autogenerated: boolean;
    deliveryPrice: number;
  };
}

interface EpicentrOrder {
  id: string;
  externalId: string;
  companyId: string;
  legalEntityId: number;
  trustedCompany: boolean;
  customerId: string;
  assignee: {
    firstName: string;
    lastName: string;
    avatar: string;
    userId: string;
  };
  comment: string;
  commentsCount: number;
  number: string;
  createdAt: string;
  updatedAt: string;
  statusCode: string;
  callStatus: string;
  subtotal: number;
  payed: boolean;
  skipCustomerContact: boolean;
  items: EpicentrOrderItem[];
  address: EpicentrOrderAddress;
}

interface EpicentrOrdersResponse {
  current: string;
  next: string;
  prev: string;
  last: string;
  limit: number;
  items: EpicentrOrder[];
}

interface EpicentrSettlement {
  id: string;
  name: string;
  region: string;
  limit: number;
  offset: number;
  total: number;
  items: {
    id: string;
    name: string;
    region: string;
  }[];
}

interface EpicentrOffice {
  id: string;
  settlementId: string;
  title: string;
  address: string;
  externalId: string;
  longitude: number;
  latitude: number;
}

class EpicentrAPI {
  private static instance: EpicentrAPI;
  private token: string;
  private cache: Map<string, { data: EpicentrSettlement[] | EpicentrOffice[], timestamp: number }> = new Map();
  private lastRequestTime: number = 0;
  private CACHE_DURATION = 5 * 60 * 1000; // 5 minutes
  private REQUEST_DELAY = 1000; // 1 second delay between requests
  
  private constructor() {
    if (typeof window !== 'undefined') {
      throw new Error('EpicentrAPI can only be used on the server side');
    }
    
    const token = process.env.EPICENTR_TOKEN;
    if (!token) {
      throw new Error('EPICENTR_TOKEN is not set in environment variables');
    }
    
    this.token = token;
    console.log('Epicentr token', this.token);
  }
  
  static getInstance(): EpicentrAPI {
    if (!EpicentrAPI.instance) {
      EpicentrAPI.instance = new EpicentrAPI();
    }
    return EpicentrAPI.instance;
  }

  async checkToken() {
    try {
      const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
      const response = await axios.get(`${baseUrl}/orders`, {
        headers: {
          'Authorization': `Bearer ${this.token}`,
          'Content-Type': 'application/json'
        }
      });
      return response.status === 200;
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error('Failed to check Epicentr connection:', error.message);
      } else {
        console.error('Failed to check Epicentr connection:', error);
      }
      return false;
    }
  }

  async getOrders() {
    try {
      const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
      const fullUrl = `${baseUrl}/v3/oms/orders`;
      console.log('Attempting to fetch from:', fullUrl);
      const response = await axios.get<EpicentrOrdersResponse>(fullUrl, {
        headers: {
          'Authorization': `Bearer ${this.token}`,
          'Content-Type': 'application/json'
        }
      });

      if (!response.data.items) {
        throw new Error('Failed to fetch orders from Epicentr');
      }

      if (!Array.isArray(response.data.items)) {
        throw new Error('Invalid response format from Epicentr API');
      }

      return { error: undefined, data: response.data.items };
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error('Failed to fetch Epicentr orders:', error.message);
        return { error: error.message, data: undefined };
      } else {
        console.error('Failed to fetch Epicentr orders:', error);
        return { error: 'Unknown error in getOrders', data: undefined };
      }
    }
  }

  async getOrderById(id: string) {
    try {
      const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
      const response = await axios.get<{ order: EpicentrOrder }>(`${baseUrl}/orders/${id}`, {
        headers: {
          'Authorization': `Bearer ${this.token}`,
          'Content-Type': 'application/json'        
        }
      });

      if (!response.data || !response.data.order) {
        throw new Error('Failed to fetch order from Epicentr');
      }

      return { error: undefined, data: response.data.order };
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error(`Failed to fetch Epicentr order ${id}:`, error.message);
        return { error: error.message, data: undefined };
      } else {
        console.error(`Failed to fetch Epicentr order ${id}:`, error);
        return { error: 'Unknown error in getOrderById', data: undefined };
      }
    }
  }

  async getSettlements(provider: string) {
    try {
      const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
      const response = await axios.get<EpicentrSettlement[]>(
        `${baseUrl}/v2/deliveries/${provider}/settlements`,
        {
          headers: {
            'Authorization': `Bearer ${this.token}`,
            'Content-Type': 'application/json'
          }
        }
      );
      return { error: undefined, data: response.data };
    } catch (error) {
      console.error('Failed to fetch settlements:', error);
      return { error: 'Failed to fetch settlements', data: undefined };
    }
  }

  async getOffices(postOfficeProvider: string, settlementId: string) {
    try {
      const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
      const response = await axios.get<{ items: EpicentrOffice[] }>(
        `${baseUrl}/v2/deliveries/${postOfficeProvider}/settlements/${settlementId}/offices`,
        {
          headers: {
            'Authorization': `Bearer ${this.token}`,
            'Content-Type': 'application/json'
          }
        }
      );
      return { error: undefined, data: response.data.items };
    } catch (error) {
      console.error('Failed to fetch offices:', error);
      return { error: 'Failed to fetch offices', data: undefined };
    }
  }

  async getDeliveryAddress(order: EpicentrOrder) {
    try {
      const provider = order.address.shipment.provider;
      const settlementId = order.address.shipment.settlementId;
      const officeId = order.address.shipment.officeId;
      console.log('officeId', officeId);

      // Get office details
      const officeResponse = await this.getOffices(provider, settlementId);
      const office = officeResponse.data?.find(o => o.id === officeId);

      if (!office) {
        return {
          error: undefined,
          data: {
            provider: provider,
            officeAddress: 'Уточнюйте на сайті епіцентра',
            officeName: 'Уточнюйте на сайті епіцентра',
            postNumber: order.address.shipment.number // This is the post office number/tracking number
          }
        };
      }

      return {
        error: undefined,
        data: {
          provider: provider,
          officeAddress: office?.address,
          officeName: office?.title,
          postNumber: order.address.shipment.number // This is the post office number/tracking number
        }
      };
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error('Failed to get delivery address:', error.message);
        return { error: error.message, data: undefined };
      } else {
        console.error('Failed to get delivery address:', error);
        return { error: 'Failed to get delivery address', data: undefined };
      }
    }
  }

  async getHardcodedStatuses() {
    return { 
      error: undefined, 
      data: [
        { id: 'new', title: 'Новий' },
        { id: 'confirmed_by_merchant', title: 'Підтверджено продавцем' },
        { id: 'confirmed', title: 'Підтверджено' },
        { id: 'sent', title: 'Відправлено' },
        { id: 'delivered', title: 'Доставлено' },
        { id: 'completed', title: 'Завершено' },
        { id: 'closed', title: 'Закрито' },
        { id: 'canceled', title: 'Скасовано' },
        { id: 'returned', title: 'Повернено' },
        { id: 'return_requested', title: 'Запит на повернення' },
        { id: 'canceled_by_merchant', title: 'Скасовано продавцем' },
        { id: 'completed_merchant_rejection', title: 'Завершено (відмова продавця)' },
        { id: 'closed_merchant_rejection', title: 'Закрито (відмова продавця)' }
      ] 
    };
  }

  async getOrderStatuses(orderId: string) {
    try {
      const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
      console.log('epicentr api url', baseUrl);
      const response = await axios.get<{ allowedStatuses: string[] }>(
        `${baseUrl}/v2/oms/orders/${orderId}/allowed-statuses`,
        {
          headers: {
            'Authorization': `Bearer ${this.token}`,
            'Content-Type': 'application/json'
          }
        }
      ).catch(error => {
        if (error.response?.status === 404) {
          throw new Error(error.response.data?.message || 'Statuses not found');
        }
        throw error;
      });

      console.log('response.data', response.data);
      return { error: undefined, data: response.data.allowedStatuses };
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error(`Failed to fetch statuses for order ${orderId}:`, error.message);
        return { error: error.message, data: undefined };
      }
      console.error(`Failed to fetch statuses for order ${orderId}:`, error);
      return { error: 'Unknown error in getOrderStatuses', data: undefined };
    }
  }

  async setOrderStatus(orderId: string, statusCode: string): Promise<{ error: string | null, data: boolean | null }> {
    try {
      const baseUrl = process.env.EPICENTR_API_URL;
      const response = await axios.patch(`${baseUrl}/v2/oms/orders/${orderId}/change-status/to/${statusCode}`, {
        headers: { Authorization: `Bearer ${this.token}` }
      });
      return { error: null, data: response.status == 202 ? true : false };
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error(`Status update failed for ${orderId}:`, error.message);
        return { error: error.message, data: null };
      } else {
        console.error(`Status update failed for ${orderId}:`, error);
        return { error: 'Failed to update Epicentr status', data: null };
      }
    }
  } 
}

const api = EpicentrAPI.getInstance();

export async function getPaymentSettings(companyId: string) {
  try {
    const baseUrl = process.env.EPICENTR_API_URL?.replace(/\/$/, '');
    const response = await axios.get(`${baseUrl}/v3/payments/companies/${companyId}`, {
      headers: {
        'Authorization': `Bearer ${process.env.EPICENTR_TOKEN}`,
        'Content-Type': 'application/json'
      }
    });
    return { error: undefined, data: response.data };
  } catch (error: unknown) {
    if (error instanceof Error) {
      console.error('Failed to get payment settings:', error.message);
      return { error: error.message, data: undefined };
    } else {
      console.error('Failed to get payment settings:', error);
      return { error: 'Failed to get payment settings', data: undefined };
    }
  }
}

async function processOrder(epicentrOrder: EpicentrOrder) {
  console.log('epicentrOrder', epicentrOrder);
  const existingOrders = await authenticatedCall(async () => {
    return await pb.collection('orders').getList(1, 1, {
      filter: `source = "pj9sejm9vqtu8xq" && orderNumber = "${epicentrOrder.number}"`
    });
  });

  if (existingOrders.items.length > 0) {
    return;
  }

  const defaultCurrency = await authenticatedCall(async () => {
    return await pb.collection('currency_options').getList(1, 1, {
      filter: "isDefault = true"
    });
  });

  if (defaultCurrency.items.length === 0) {
    throw new Error('No default currency found');
  }

  let defaultStatus = '';
  try {
    const statuses = await authenticatedCall(async () => {
      return await pb.collection('status_options').getList(1, 50, {
        sort: '+priority',
        limit: 1
      });
    });
    
    if (statuses.items.length > 0) {
      defaultStatus = statuses.items[0].id;
    } else {
      console.warn('No statuses found, using fallback status');
    }
  } catch (error) {
    console.warn('Failed to fetch statuses, using fallback status:', error);
  }

  const defaultDeliveryMethod = await getDefaultDeliveryMethod();
  if (!defaultDeliveryMethod.data?.id) {
    throw new Error('No default delivery method found');
  }

  const deliveryAddress = await getDeliveryAddress(epicentrOrder);
  await new Promise(resolve => setTimeout(resolve, 3000));

  const fullName = [epicentrOrder.address.firstName, epicentrOrder.address.lastName, epicentrOrder.address.patronymic]
    .filter(Boolean)
    .join(' ') || 'Unknown';

  const orderData = {
    source: 'pj9sejm9vqtu8xq',
    orderNumber: epicentrOrder.number,
    marketplaceId: epicentrOrder.id,
    phoneNumber: epicentrOrder.address.phone,
    fullName,
    products: epicentrOrder.items.map(item => ({
      title: item.title,
      quantity: item.quantity,
      price: item.price
    })),
    numberOfItems: epicentrOrder.items.reduce((sum, item) => sum + item.quantity, 0),
    amount: epicentrOrder.subtotal,
    paymentMethod: mapPaymentProvider(epicentrOrder.address.shipment.paymentProvider),
    deliveryMethod: mapDeliveryProvider(epicentrOrder.address.shipment.provider),
    status: defaultStatus,
    currency: defaultCurrency.items[0].id,
    notes: epicentrOrder.comment || '',
    deliveryPostNumber: deliveryAddress.data?.officeAddress || 'Уточнюйте на сайті епіцентра',
    mergeSource: 'none',
    mergeStatus: 'none',
    productionCost: 0,
  };

  const validationResult = orderSchema.safeParse({
    ...orderData,
    mergeSource: orderData.mergeSource || 'none',
    mergeStatus: orderData.mergeStatus || 'none'
  });
  if (!validationResult.success) {
    appendFileSync(
      'orders-validation-errors.log',
      `${new Date().toISOString()} - Validation Error:\n${JSON.stringify({
        orderData,
        validationErrors: validationResult.error.format()
      }, null, 2)}\n\n`
    );
    throw new Error(`Invalid order data: ${validationResult.error.message}`);
  }

  await authenticatedCall(async () => {
    return await pb.collection('orders').create(orderData);
  });
}


export async function syncOrders() {
  try {
    const epicentrOrders = await getOrders();
    if (!epicentrOrders.data) {
      throw new Error('Failed to fetch Epicentr orders');
    }
    
    let syncedOrders = 0;
    let failedOrders = 0;

    for (const order of epicentrOrders.data) {
      try {
        await processOrder(order);
        syncedOrders++;
      } catch (error) {
        console.error(`Failed to process epicentr order ${order.id}:`, error);
        failedOrders++;
      }
    }
    
    await pb.collection('sync_records').create({
      source: 'pj9sejm9vqtu8xq',
      orders_processed: syncedOrders,
      orders_failures: failedOrders
    });
    
    return { success: true, syncedOrders, failedOrders };
  } catch (error) {
    console.error('Failed to sync orders:', error);
    return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
  }
}

const DELIVERY_PROVIDER_MAP: Record<string, string> = {
  'nova_poshta': 'z3r33isgncbc95d',
  'ukrposhta': 'ia2pd4yet3pmvba', 
  'pickup': 'zb8exkxxzupmihf',
  'meest': 'tkg5cvs2n3cbuf0',
  'cvz_epicentr': 'psyomk007l2vjxg', //pickup Meest-Epicentr
  'parcel_box_epicentr': 'fw7z9ewvh5pqseq' //dropbox Meest-Epicentr
};

function mapDeliveryProvider(epicentrProvider: string): string {
  return DELIVERY_PROVIDER_MAP[epicentrProvider] || epicentrProvider;
}

const PAYMENT_PROVIDER_MAP: Record<string, string> = {
  'easypay': 'lc78mu3yrwvufkl',
  'monobank': '2o88s38kkayb2qc',
  'pay_on_delivery': '96lr1fgyn4kolyh'
};

function mapPaymentProvider(epicentrProvider: string): string {
  return PAYMENT_PROVIDER_MAP[epicentrProvider] || epicentrProvider;
}

// Export functions
export async function getOrders() {
  return api.getOrders();
}

export async function getOrderById(id: string) {
  return api.getOrderById(id);
}

export async function checkConnection() {
  return api.checkToken();
}

export async function getSettlements(provider: string) {
  return api.getSettlements(provider);
}

export async function getOffices(postOfficeProvider: string, settlementId: string) {
  return api.getOffices(postOfficeProvider, settlementId);
}

export async function getDeliveryAddress(order: EpicentrOrder) {
  return api.getDeliveryAddress(order);
}

export async function getOrderStatuses(orderId: string) {
  return api.getOrderStatuses(orderId);
}

export async function setOrderStatus(orderId: string, statusCode: string) {
  return api.setOrderStatus(orderId, statusCode);
}

export async function getHardcodedStatuses() {
  return api.getHardcodedStatuses();
}